services:

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mariadb
    volumes:
    - ./data:/docker-entrypoint-initdb.d

  phpmyadmin:
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8181:80
    restart: always
    volumes:
      - /sessions

  wordpress:
    environment:
      WORDPRESS_DB_PASSWORD: password
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - ./app/wp-content/themes/school-self-evaluation:/var/www/html/wp-content/themes/school-self-evaluation

version: '2'
